services:
    database:
        build: ./db
        ports:
            - "5432:5432" # map database:5432 to host:5432
        user: postgres
        healthcheck:
          test: ["CMD-SHELL", "pg_isready", "-U postgres"]
          interval: 10s
          timeout: 5s
          retries: 5
    scraper:
        build: ./scraper
        depends_on:
            database:
                condition: service_healthy
