/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package server;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.scheduling.annotation.EnableAsync;

@SpringBootApplication
@EnableAsync
public class App {
    /**
     * Connects to the database, then if successful start the REST server.
     * @param args
     */
    public static void main(String[] args) {
        System.out.println("hello world");
        SpringApplication.run(RestServer.class, args);
        //Database.testing();

        //TODO Spring
        //TODO DB access
        //TODO YR ACCESS
    }


}
