/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package server;
import java.io.IOException;
import java.net.URI;
import java.net.http.*;
import java.nio.file.Path;
import java.nio.file.Paths;

public class App {

    public static void main(String[] args) {
        System.out.println("hello world");

        //TODO Spring
        //TODO DB access
        //TODO YR ACCESS
    }
}
